# -*- coding: utf-8 -*-
"""Crescente e Decrescente.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqIhk66Saz3jXm-aQ1-wIMAi0nOSr-9y
"""

"""
Este programa tem por objetivo receber 3 números inteiros positivos do usuário
de uma só vez e imprimi-los iniciamente em ordem descrescente e logo em seguida
em ordem crescente, cada lista ordenada em uma linha.
"""


def main():
  num = input().split()
  a = int(num[0])
  b = int(num[1])
  c = int(num[2])
  print(decresc(a, b, c))
  print(cresc(a, b, c))

def cresc(x: int, y: int, z: int) -> int:
  Mx2 = max(x, y)
  Mn2 = -max(-x, -y)

  Mx3 = max(Mx2,z)
  Mn = -max(-Mx2, -z)
  Mn3 = -max(-Mn2, -z)

  Md = max(Mn2,Mn)
  Md2 = -max(-Mn2, -Mn)

  return Mn3, Md, Mx3

def decresc(x: int, y: int, z: int) -> int:
  Mx2 = max(x, y)
  Mn2 = -max(-x, -y)

  Mx3 = max(Mx2,z)
  Mn = -max(-Mx2, -z)
  Mn3 = -max(-Mn2, -z)

  Md = max(Mn2,Mn)
  Md2 = -max(-Mn2, -Mn)

  return Mx3, Md, Mn3

main()

num = input().split()
a = int(num[0])
b = int(num[1])
c = int(num[2])

Mx2 = max(a, b)
Mn2 = -max(-a, -b)

Mx3 = max(Mx2,c)
Mn = -max(-Mx2, -c)
Mn3 = -max(-Mn2, -c)

Md = max(Mn,Mn3)
Md2 = -max(-Mn2, -Mn)

print(Mn3)
print(Md)
print(Mx3)